"""add students

Revision ID: 740eaeda29b6
Revises: a1abea1bd1a6
Create Date: 2023-04-11 22:38:24.787128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740eaeda29b6'
down_revision = 'a1abea1bd1a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
